services:
  api:
    build: .
    container_name: tickets_api_service
    ports:
      - "4321:4321"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    restart: always
